### ISSUE TITLE
Suggestion: links should open in a new tab

### ISSUE THREAD

**Issue by LucaBoschetto** [ThinkerDreamer/animated-spoon#9]
Suggestion: all the links on this page should open in a new tab (target="_blank"), so that when one closes it they go back to this menu page.

**Comment by ThinkerDreamer** [comment]
Yeah! Good idea. It seems that now we need to add `rel="noopener noreferrer"` too to avoid a security vulnerability.
More info here: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by ThinkerDreamer** [comment]
This was fixed in [commit #0517646dea61f621e005cabaaeb5bb8078391161](https://github.com/ThinkerDreamer/animated-spoon/commit/0517646dea61f621e005cabaaeb5bb8078391161)
